# Generated by Django 4.2.15 on 2024-08-13 00:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gigsweep_django_backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistgigapplication',
            name='applied_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
