# Generated by Django 4.2.6 on 2023-10-22 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigsweep_django_backend', '0002_artistlistedgig_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artistlistedgig',
            name='description',
        ),
        migrations.RemoveField(
            model_name='venuelistedgig',
            name='description',
        ),
        migrations.AlterField(
            model_name='artist',
            name='bio',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='facebook',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='twitter',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='youtube',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='artistwrittenreview',
            name='review',
            field=models.TextField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='address',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='bio',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='facebook',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='twitter',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='youtube',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='venuewrittenreview',
            name='review',
            field=models.TextField(max_length=10000, null=True),
        ),
    ]
