# Generated by Django 4.2.6 on 2024-01-09 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gigsweep_django_backend', '0002_chatmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
