# Generated by Django 4.2.15 on 2024-08-16 00:46

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gigsweep_django_backend', '0003_alter_artistlistedgig_country_of_venue'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistGig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_gig', models.DateField(null=True)),
                ('venue_name', models.CharField(max_length=100, null=True)),
                ('country_of_venue', models.CharField(choices=[('England', 'England'), ('Wales', 'Wales'), ('Scotland', 'Scotland'), ('Northern Ireland', 'Northern Ireland')], max_length=100, null=True)),
                ('genre_of_gig', models.CharField(choices=[('Rock', 'Rock'), ('Pop', 'Pop'), ('Jazz', 'Jazz'), ('Country', 'Country'), ('Hip Hop', 'Hip Hop'), ('R&B', 'R&B'), ('Electronic', 'Electronic'), ('Classical', 'Classical'), ('Reggae', 'Reggae'), ('Metal', 'Metal'), ('Folk', 'Folk'), ('Blues', 'Blues'), ('World Music', 'World Music')], max_length=50, null=True)),
                ('type_of_gig', models.CharField(choices=[('Original Music', 'Original Music'), ('Covers', 'Covers'), ('Both', 'Both')], max_length=50, null=True)),
                ('type_of_artist', models.CharField(choices=[('Full band', 'Full band'), ('Solo artist', 'Solo artist'), ('Duo', 'Duo')], max_length=50, null=True)),
                ('payment', models.IntegerField(null=True)),
                ('user_type', models.CharField(choices=[('Artist', 'Artist'), ('Venue', 'Venue')], max_length=50, null=True)),
                ('num_applications', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(null=True)),
                ('status', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Active', 'Active'), ('Transferred', 'Transferred'), ('Past', 'Past')], default='Active', max_length=200)),
                ('transfer_history', models.TextField(blank=True, null=True)),
                ('current_artist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_artist_gigs', to='gigsweep_django_backend.artist')),
                ('original_artist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='original_artist_gigs', to='gigsweep_django_backend.artist')),
                ('previous_artists', models.ManyToManyField(blank=True, related_name='previous_artist_gigs', to='gigsweep_django_backend.artist')),
                ('venue', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gigs_at_venue', to='gigsweep_django_backend.venue')),
            ],
        ),
        migrations.AlterField(
            model_name='artistgigapplication',
            name='artist_gig',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='gigsweep_django_backend.artistgig'),
        ),
        migrations.DeleteModel(
            name='ArtistListedGig',
        ),
    ]
