# Generated by Django 4.2.6 on 2023-10-22 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigsweep_django_backend', '0003_remove_artistlistedgig_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistlistedgig',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='venuelistedgig',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='bio',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='facebook',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='twitter',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='youtube',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artistwrittenreview',
            name='review',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='unavailability',
            name='reason',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='bio',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='facebook',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='twitter',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='youtube',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='venuewrittenreview',
            name='review',
            field=models.TextField(null=True),
        ),
    ]
