# Generated by Django 4.2.6 on 2023-10-22 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigsweep_django_backend', '0004_artistlistedgig_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipoptions',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
