# Generated by Django 4.2.6 on 2024-01-15 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigsweep_django_backend', '0004_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='upcoming_gigs',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
