# Generated by Django 4.2.15 on 2024-08-18 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigsweep_django_backend', '0004_artistgig_alter_artistgigapplication_artist_gig_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistgig',
            name='advertised_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artistgig',
            name='is_advertised',
            field=models.BooleanField(default=False),
        ),
    ]
