# Generated by Django 4.2.6 on 2024-01-31 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gigsweep_django_backend', '0005_artist_upcoming_gigs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
