# Generated by Django 4.2.6 on 2023-10-22 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gigsweep_django_backend', '0005_alter_membershipoptions_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artistgigapplication',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='artistgigapplication',
            name='artist_gig',
        ),
        migrations.RemoveField(
            model_name='artistlistedgig',
            name='artist',
        ),
        migrations.DeleteModel(
            name='ArtistWrittenReview',
        ),
        migrations.DeleteModel(
            name='MembershipOptions',
        ),
        migrations.DeleteModel(
            name='NewsletterSignup',
        ),
        migrations.RemoveField(
            model_name='unavailability',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='venuegigapplication',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='venuegigapplication',
            name='venue_gig',
        ),
        migrations.RemoveField(
            model_name='venuelistedgig',
            name='venue',
        ),
        migrations.DeleteModel(
            name='VenueWrittenReview',
        ),
        migrations.DeleteModel(
            name='ArtistGigApplication',
        ),
        migrations.DeleteModel(
            name='ArtistListedGig',
        ),
        migrations.DeleteModel(
            name='Unavailability',
        ),
        migrations.DeleteModel(
            name='Venue',
        ),
        migrations.DeleteModel(
            name='VenueGigApplication',
        ),
        migrations.DeleteModel(
            name='VenueListedGig',
        ),
    ]
