# Generated by Django 4.2.6 on 2023-10-22 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigsweep_django_backend', '0006_remove_artistgigapplication_artist_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership_id', models.IntegerField(null=True)),
                ('type_of_user', models.CharField(choices=[('Artist', 'Artist'), ('Venue', 'Venue')], max_length=50, null=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(null=True)),
                ('price', models.CharField(max_length=50, null=True)),
                ('disclosure', models.CharField(max_length=150, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Artist',
        ),
    ]
