# Generated by Django 4.2.6 on 2024-02-03 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gigsweep_django_backend', '0006_delete_chatmessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venue',
            old_name='image',
            new_name='profile_picture',
        ),
    ]
