# Generated by Django 4.2.6 on 2024-02-03 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gigsweep_django_backend', '0007_rename_image_venue_profile_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venue',
            old_name='profile_picture',
            new_name='image',
        ),
    ]
