# Generated by Django 4.2.15 on 2024-08-21 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gigsweep_django_backend', '0007_contactgigsweep'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactGigSweep',
            new_name='ContactQuery',
        ),
    ]
