# Generated by Django 4.2.15 on 2024-08-21 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigsweep_django_backend', '0008_rename_contactgigsweep_contactquery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artistgig',
            old_name='description',
            new_name='notes_about_gig',
        ),
        migrations.AddField(
            model_name='artistgig',
            name='reason_for_advertising',
            field=models.TextField(null=True),
        ),
    ]
