# Generated by Django 4.2.6 on 2024-03-10 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigsweep_django_backend', '0008_rename_profile_picture_venue_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='password',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
