# Generated by Django 4.2.6 on 2024-03-15 01:42

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gigsweep_django_backend', '0009_alter_artist_email_alter_artist_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistlistedgig',
            name='status',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Active', 'Active'), ('Transferred', 'Transferred'), ('Past', 'Past')], max_length=200),
        ),
    ]
