# Generated by Django 4.2.15 on 2024-08-22 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gigsweep_django_backend', '0010_alter_artistgig_notes_about_gig_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistgig',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gigs_at_venue', to='gigsweep_django_backend.venue'),
        ),
    ]
