# Generated by Django 4.2.15 on 2024-08-27 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigsweep_django_backend', '0011_alter_artistgig_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='venuelistedgig',
            name='duration_of_gig',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='venuelistedgig',
            name='time_of_gig',
            field=models.TimeField(null=True),
        ),
    ]
