# Generated by Django 4.2.15 on 2024-08-27 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gigsweep_django_backend', '0012_venuelistedgig_duration_of_gig_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VenueGig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_gig', models.DateField(null=True)),
                ('time_of_gig', models.TimeField(null=True)),
                ('duration_of_gig', models.PositiveIntegerField(null=True)),
                ('country_of_venue', models.CharField(choices=[('England', 'England'), ('Wales', 'Wales'), ('Scotland', 'Scotland'), ('Northern Ireland', 'Northern Ireland')], max_length=100, null=True)),
                ('genre_of_gig', models.CharField(choices=[('Rock', 'Rock'), ('Pop', 'Pop'), ('Jazz', 'Jazz'), ('Country', 'Country'), ('Hip Hop', 'Hip Hop'), ('R&B', 'R&B'), ('Electronic', 'Electronic'), ('Classical', 'Classical'), ('Reggae', 'Reggae'), ('Metal', 'Metal'), ('Folk', 'Folk'), ('Blues', 'Blues'), ('World Music', 'World Music')], max_length=50, null=True)),
                ('type_of_gig', models.CharField(choices=[('Original Music', 'Original Music'), ('Covers', 'Covers'), ('Both', 'Both')], max_length=50, null=True)),
                ('artist_type', models.CharField(choices=[('Full band', 'Full band'), ('Solo artist', 'Solo artist'), ('Duo', 'Duo')], max_length=50, null=True)),
                ('payment', models.IntegerField(null=True)),
                ('user_type', models.CharField(choices=[('Artist', 'Artist'), ('Venue', 'Venue')], max_length=50, null=True)),
                ('num_applications', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(null=True)),
                ('is_advertised', models.BooleanField(default=False)),
                ('advertised_at', models.DateTimeField(blank=True, null=True)),
                ('artist_needed', models.BooleanField(default=False)),
                ('required_genre', models.CharField(blank=True, choices=[('Rock', 'Rock'), ('Pop', 'Pop'), ('Jazz', 'Jazz'), ('Country', 'Country'), ('Hip Hop', 'Hip Hop'), ('R&B', 'R&B'), ('Electronic', 'Electronic'), ('Classical', 'Classical'), ('Reggae', 'Reggae'), ('Metal', 'Metal'), ('Folk', 'Folk'), ('Blues', 'Blues'), ('World Music', 'World Music')], max_length=50, null=True)),
                ('required_artist_type', models.CharField(blank=True, choices=[('Full band', 'Full band'), ('Solo artist', 'Solo artist'), ('Duo', 'Duo')], max_length=50, null=True)),
                ('applications_open_until', models.DateField(blank=True, null=True)),
                ('venue', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='venue_gigs', to='gigsweep_django_backend.venue')),
            ],
        ),
        migrations.AlterField(
            model_name='venuegigapplication',
            name='venue_gig',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gigsweep_django_backend.venuegig'),
        ),
        migrations.DeleteModel(
            name='VenueListedGig',
        ),
    ]
