# Generated by Django 4.2.6 on 2024-06-28 21:36

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gigsweep_django_backend', '0012_alter_venue_email_alter_venue_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistgigapplication',
            name='message',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='artistgigapplication',
            name='original_artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='original_gig_applications', to='gigsweep_django_backend.artist'),
        ),
        migrations.AddField(
            model_name='artistgigapplication',
            name='status',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Active', 'Active'), ('Transferred', 'Transferred'), ('Past', 'Past')], max_length=200),
        ),
        migrations.AddField(
            model_name='artistgigapplication',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gigsweep_django_backend.venue'),
        ),
        migrations.AlterField(
            model_name='artistgigapplication',
            name='artist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='gigsweep_django_backend.artist'),
        ),
        migrations.AlterField(
            model_name='artistgigapplication',
            name='artist_gig',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='gigsweep_django_backend.artistlistedgig'),
        ),
    ]
