# Generated by Django 4.2.6 on 2024-06-28 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gigsweep_django_backend', '0013_artistgigapplication_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistgigapplication',
            name='artist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gigsweep_django_backend.artist'),
        ),
        migrations.AlterField(
            model_name='artistgigapplication',
            name='artist_gig',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artists', to='gigsweep_django_backend.artistlistedgig'),
        ),
    ]
