# Generated by Django 4.2.6 on 2024-07-01 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gigsweep_django_backend', '0017_alter_artistgigapplication_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistlistedgig',
            name='venue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gigs_at_venue', to='gigsweep_django_backend.venue'),
        ),
    ]
