# Generated by Django 4.2.6 on 2024-07-01 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gigsweep_django_backend', '0018_artistlistedgig_venue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artistlistedgig',
            old_name='venue',
            new_name='venue_id',
        ),
    ]
