# Generated by Django 4.2.6 on 2024-07-13 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gigsweep_django_backend', '0021_venuenotification_artistnotification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artistlistedgig',
            name='venue_name',
        ),
    ]
