# Generated by Django 4.2.6 on 2024-07-13 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigsweep_django_backend', '0022_remove_artistlistedgig_venue_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistlistedgig',
            name='venue_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
