# Generated by Django 4.2.6 on 2024-07-13 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gigsweep_django_backend', '0024_rename_venue_artistlistedgig_venue_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artistlistedgig',
            old_name='venue_id',
            new_name='venue',
        ),
    ]
