# Generated by Django 4.2.6 on 2024-07-13 01:37

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gigsweep_django_backend', '0025_rename_venue_id_artistlistedgig_venue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistlistedgig',
            name='status',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Active', 'Active'), ('Transferred', 'Transferred'), ('Past', 'Past')], default='Active', max_length=200),
        ),
    ]
