# Generated by Django 4.2.6 on 2024-07-17 16:04

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gigsweep_django_backend', '0028_alter_venuenotification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venuenotification',
            name='notification_type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('GIG_TRANSFER', 'Gig Transfer'), ('VENUE_ADVERTISED_GIG', 'Venue Advertised Gig'), ('GENERAL_GIGSWEEP_UPDATES', 'General Gigsweep Updates'), ('TEST', 'Test')], max_length=200),
        ),
    ]
