# Generated by Django 4.2.6 on 2024-07-17 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigsweep_django_backend', '0029_alter_venuenotification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='venuenotification',
            name='if_artist_listed_gig',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
