# Generated by Django 4.2.6 on 2024-07-17 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gigsweep_django_backend', '0031_rename_if_artist_listed_gig_venuenotification_if_gig_advertised_by_artist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venuenotification',
            name='if_artist_gig_application_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='venue_notifications', to='gigsweep_django_backend.artistgigapplication'),
        ),
    ]
